### ISSUE TITLE
Small Tap Targets

### ISSUE THREAD

**Issue by benyanke** [bbloomf/compline#3]
What's your thoughts on doing more mobile friendly selectors? I'm noticing on my phone that the tap targets (as google calls them) are a bit small. Would you take a pull request if I worked on that for all the selectors throughout the page?

**Comment by bbloomf** [comment]
That's a good point, and I've been thinking about using the bootstrap css library and styling those radio buttons as vertical button groups, which would also make them a bit more mobile friendly in terms of tap target size.  If you were to implement something like that, I would accept a pull request.

**Comment by benyanke** [comment]
I was thinking bootstrap too. I'll take a look at it when I get a bit of free time.

**Comment by bbloomf** [comment]
I ended up changing these all to bootstrap vertical button groups.  Let me know what you think.  If you want to compare it to the old version, you can still get that here: https://rawgit.com/bbloomf/compline/before-bootstrap/index.html
