### ISSUE TITLE
Missing psalms 

### ISSUE THREAD

**Issue by emilysan** [bbloomf/compline#6]
Hello! My friends and I are very grateful for this wonderful app! During the quarantine we have been video calling and chanting compline together every night using this app. However, about a week ago, the psalms on the iPhones disappears. The android users still have the app as normal, but for the rest of us it is missing. Despite deleting and re-downloading, changing the settings, and other attempts, we can’t get them to return. We’d be grateful for anything you can do to help us! God bless! 
![6945838F-A174-41E0-A506-5DBA69F457F4](https://user-images.githubusercontent.com/64825300/81035844-88fd0580-8e51-11ea-894a-10ff2bdafa60.png)
![A5C81D2C-E168-4503-94A0-856E56C31B93](https://user-images.githubusercontent.com/64825300/81035850-8bf7f600-8e51-11ea-8644-195f35dbb76c.png)
![EC4914C1-9CFC-41F4-82FC-1432D5940AEE](https://user-images.githubusercontent.com/64825300/81035852-8dc1b980-8e51-11ea-84c5-09d93d1ed034.png)

**Comment by bbloomf** [comment]
Thank you for this bug report.  I will take a look and figure out what happened.  I did put up a new release about a week ago, and it must have broken something.

Thanks for the detailed screenshots as well.

**Comment by bbloomf** [comment]
OK, it's fixed, but it needs to get approved by Apple for the App Store.  In the meantime, I forgot to mention that you can go to the website version here: http://compline.us.to/ and that will work right now.
